// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nlayer.Repository;

#nullable disable

namespace Nlayer.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230923114947_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Nlayer.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 9, 23, 14, 49, 47, 153, DateTimeKind.Local).AddTicks(181),
                            Name = "Kalemler"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 9, 23, 14, 49, 47, 153, DateTimeKind.Local).AddTicks(195),
                            Name = "Kitaplar"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 9, 23, 14, 49, 47, 153, DateTimeKind.Local).AddTicks(196),
                            Name = "Defterler"
                        });
                });

            modelBuilder.Entity("Nlayer.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 9, 23, 14, 49, 47, 153, DateTimeKind.Local).AddTicks(527),
                            Name = "Kalem 1",
                            Price = 100m,
                            Stock = 34
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 9, 23, 14, 49, 47, 153, DateTimeKind.Local).AddTicks(530),
                            Name = "Kalem 2",
                            Price = 400m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 9, 23, 14, 49, 47, 153, DateTimeKind.Local).AddTicks(532),
                            Name = "Kalem 3",
                            Price = 130m,
                            Stock = 24
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 9, 23, 14, 49, 47, 153, DateTimeKind.Local).AddTicks(533),
                            Name = "Kitap 1",
                            Price = 130m,
                            Stock = 24
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 9, 23, 14, 49, 47, 153, DateTimeKind.Local).AddTicks(534),
                            Name = "Kitap 2",
                            Price = 130m,
                            Stock = 24
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 9, 23, 14, 49, 47, 153, DateTimeKind.Local).AddTicks(535),
                            Name = "Defter 2",
                            Price = 130m,
                            Stock = 24
                        });
                });

            modelBuilder.Entity("Nlayer.Core.Entities.ProductFeture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("ProductFetures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Mor",
                            Height = 12,
                            ProductId = 1,
                            Width = 8
                        },
                        new
                        {
                            Id = 2,
                            Color = "Mavi",
                            Height = 14,
                            ProductId = 2,
                            Width = 9
                        });
                });

            modelBuilder.Entity("Nlayer.Core.Entities.Product", b =>
                {
                    b.HasOne("Nlayer.Core.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Nlayer.Core.Entities.ProductFeture", b =>
                {
                    b.HasOne("Nlayer.Core.Entities.Product", "Product")
                        .WithOne("ProductFeture")
                        .HasForeignKey("Nlayer.Core.Entities.ProductFeture", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Nlayer.Core.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Nlayer.Core.Entities.Product", b =>
                {
                    b.Navigation("ProductFeture");
                });
#pragma warning restore 612, 618
        }
    }
}
